i have/will (had)

# /docker/capture-daemon/docker-compose.capture-daemon.yaml
# `docker compose run --rm host-init` run once after boot
services:
  host-init:
    image: alpine:3.20
    privileged: true          # needed for modprobe
    pid: host                 # so we touch host’s /proc, modules, /dev
    network_mode: none
    volumes:
      - /lib/modules:/lib/modules:ro     # allow modprobe
      - /dev:/dev                        # to list /dev/video*
    entrypoint: /bin/sh -c '
      set -e
      if ls /dev/video[0-8] >/dev/null 2>&1 ; then
          echo "⇢ Real camera detected – skipping loopback"
          exit 0
      fi
      echo "⇢ No camera – inserting v4l2loopback at /dev/video9"
      modprobe v4l2loopback devices=1 video_nr=9 card_label=NoCamera exclusive_caps=1
    '
    restart: "no"
    

i want to respect the name capture-daemon entirely

services:
  capture-daemon:
    build:
      context: ../../host/services/capture-daemon
      target: runtime
    profiles: [capture-daemon]           # only runs with --profile capture
    # -------- device access --------
    privileged: true              # simplest: exposes /dev
    # …… fine-grained alternative:
    # devices:
    #   - /dev/video0:/dev/video0
    #   - /dev/video1:/dev/video1
    volumes:
      - ./records:/records        # host path for mp4s
    environment:
      # default path inside container; you can override at launch
      CAPTURE_OUTDIR: /records
    ports:
      - "9000:9000"               # registry API
    # -------- "ephemeral" behaviour --------
    restart: "no"                 # don’t respawn automatically
    deploy:
      restart_policy:
        condition: none           # same for Swarm/Compose v3
 