# docker-compose.yml

name: That DAM Toolbox

services:
  video-api:
    build:
      context: .
      dockerfile: Dockerfile       # ← multi-arch Dockerfile, as above
      # Uncomment for server fallback:
      # args:
      #   - VIDEO_FORCE_STDHTTP=1
    image: cdaprod/video:dev
    platform: linux/arm64          # ← for Pi 5; remove for auto/amd64 dev
    ports:
      - "8080:8080"                # Expose API server (FastAPI or stdlib)
    environment:
      # Uncomment to force pure Python stdlib HTTP (for minimal or testing)
      # VIDEO_FORCE_STDHTTP: "1"
      TZ: "America/New_York"
    volumes:
      - /mnt/b/Video:/mnt/b/Video  # ← network source mount
      - ./video:/workspace/video   # ← live source mount for hot reloading
      - ./data/media:/media        # ← your media source
      - ./data/db:/workspace/db    # ← local db/data
    restart: unless-stopped
    entrypoint: ["python","-m","video"]
    command: ["serve", "--host", "0.0.0.0", "--port", "8080"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # ---- Optional one-shot CLI runner sidecar ----
  video-cli:
    image: cdaprod/video:dev
    entrypoint: ["python", "-m", "video"]
    command: ["stats"]                   # or any CLI command
    volumes:
      - ./data/media:/media
      - ./data/db:/workspace/db
    depends_on:
      - video-api
    profiles: ["cli"]                    # run with: docker compose --profile cli run video-cli