# /docker-compose.yml

name: That DAM Toolbox

services:
  video-api:
    build:
      context: .
      dockerfile: Dockerfile            # multi-arch build
    image: cdaprod/video:dev
    platform: linux/arm64               # Pi 5; drop for x86-64 dev

    ## networking
    network_mode: host                  # host-mode already exposes port 8080
    # ports: ["8080:8080"]              # <-- remove (ignored in host mode)

    ## time-zone & optional env
    environment:
      TZ: America/New_York
      # VIDEO_FORCE_STDHTTP: "1"        # enable if you want stdlib HTTP

    ## video devices (unnecessary thanks to devices_cgroup_rules)
    # devices:
    #   - /dev/video0:/dev/video0
    #   - /dev/video1:/dev/video1
    #   - /dev/vchiq:/dev/vchiq
    #   - /dev/dri:/dev/dri               # whole DRM dir ↔ encoders/GL

    ## hot-plug any /dev/video* that appears later (major 81)
    device_cgroup_rules:
      - "c 81:* rmw"

    ## add container user to the "video" group (GID 44 on Raspberry Pi OS)
    group_add:
      - "44"
    
    ## grant full device access (bind-mounting /dev/video*)
    privileged: true
    
    ## bind-mount storage & live source
    volumes:
      - /mnt/b/Video:/mnt/b/Video:rw    # B – read-write working store
      - /mnt/nas:/mnt/nas:ro            # NAS – read-only capture archive
      - ./video:/workspace/video:rw     # live code hot-reload
      - ./data/media:/media:rw          # local capture target
      - ./data/db:/workspace/db:rw      # SQLite, thumbnails, etc.

    restart: unless-stopped

    ## run the API
    entrypoint: ["python", "-m", "video"]
    command:    ["serve", "--host", "0.0.0.0", "--port", "8080"]

    ## simple health-probe
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/health || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3

  # optional one-shot CLI side-car
  video-cli:
    image: cdaprod/video:dev
    entrypoint: ["python", "-m", "video"]
    command: ["stats"]                  # any CLI verb
    volumes:
      - ./data/media:/media
      - ./data/db:/workspace/db
    depends_on: [video-api]
    profiles: ["cli"]