secrets:
  dam_ephemeral_token: { file: ./secrets/dam_token.txt }

services:
  hotspot-installer:
    image: thatdam-hotspot-installer:latest     # the image with setup.sh
    privileged: true                            # needs NET_ADMIN, etc.
    network_mode: host                          # touches wlan0 directly
    profiles: ["setup"]                         # ← won’t start in the main stack
    environment:
      SETUP_TOKEN_FILE: /run/secrets/dam_token  # setup.sh picks it up
    secrets:
      - source: dam_ephemeral_token
        target: dam_token                       # → /run/secrets/dam_token
    restart: "no"                               # it exits after writing configs