services:
  gw:
    build:
      context: docker/nginx        # Dockerfile sits here
    container_name: thatdam-gateway
    network_mode: host             # owns :80 / :443 on the Pi
    restart: unless-stopped
    depends_on:
      video-api: {condition: service_healthy}
      video-web: {condition: service_started}

    # If you choose bridge mode instead, comment network_mode and add:
    # networks: [damnet]
    # ports: ["80:80"]

    environment:
      # host-net → talk to services via 127.0.0.1
      API_HOST: "127.0.0.1"
      API_PORT: "8080"
      WEB_HOST: "127.0.0.1"
      WEB_PORT: "3000"

    volumes:
      # allow you to override nginx.tmpl without rebuilding
      - ./docker/nginx/nginx.tmpl:/etc/nginx/nginx.tmpl:ro
      - ./docker/nginx/html:/usr/share/nginx/html:ro  # optional static export
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }