services:
  nginx:
    image: nginx:latest
    profiles: [nginx]
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      # If you build static frontend into ./docker/html:
      - ./docker/html:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - video-api
      - video-web

